### ISSUE TITLE
StorybookのMSWを動作させる

### ISSUE THREAD

**Issue by mktkhr** [mktkhr/stamp-iot#177]
## 目的

- #174 にてmswを追加したが動作していないため，こちらのissueに切り出し

## 期待結果

- mswが動作していること
  - 特に，全画面で共通で呼び出される `/api/ems/session` を必ずmockしていること

**Comment by mktkhr** [comment]
## エラー1 -- 

```
prepare.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'app')
    at Object.get (prepare.js:1:41150)
    at prepare.js:1:68343
    at prepare.js:1:33614
    at prepare.js:1:33606
``` 

### 原因
- Chrome の `vuedevtools` 拡張が原因。OFFにしたら消えた。

**Comment by mktkhr** [comment]
`v1.0.0` に入れるほど急に必要ではないので，マイルストーンから解放する。
